name: DIND

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: docker://library/alpine:latest

    steps:
      - name: Run Commands
        run: |
              apk add git docker-cli
              git -- version
              docker --version
              docker ps
