name: DIND

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/raonigabriel/builder-java:latest

    steps:
      - name: Run Commands
        run: |
              git --version
              docker --version
              docker ps
