name: 'Refresh Certificate'
on:
  workflow_dispatch:

jobs:
  refresh-certificate:
    runs-on: ubuntu-22.04
    steps:
    - name: 'Install tools'
      run: pip install certbot-dns-cloudflare
    - name: 'Run Certbot'
      run: certbot --version
